import { Job } from './types';

export const MOCK_JOBS: Job[] = [
    {
        _id: "1",
        title: "Full Stack Developer Intern",
        company: "Vercel",
        companyLogo: "▲",
        location: "Bangalore · Remote",
        city: "Bangalore",
        type: "Internship",
        mode: "Remote",
        salaryMin: 30000,
        salaryMax: 45000,
        salary: "₹30K–₹45K/mo",
        description: "Work on the next generation of web development tools...",
        responsibilities: ["Build features in Next.js", "Collaborate with designers", "Fix bugs"],
        requirements: ["React knowledge", "TypeScript", "Passion for web"],
        tags: ["Next.js", "React", "TypeScript", "Tailwind"],
        openings: 2,
        deadline: "2026-05-01",
        featured: true,
        posted: "2 days ago",
        postedBy: "admin_1",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "2",
        title: "Frontend Engineer",
        company: "Stripe",
        companyLogo: "💳",
        location: "Remote",
        city: "Global",
        type: "Full-time",
        mode: "Remote",
        salaryMin: 80000,
        salaryMax: 120000,
        salary: "₹80K–₹1.2L/mo",
        description: "Help us build beautiful and functional payment interfaces...",
        responsibilities: ["Develop UI components", "Optimise performance"],
        requirements: ["JS/TS expertise", "CSS proficiency"],
        tags: ["React", "Motion", "CSS"],
        openings: 1,
        deadline: "2026-04-15",
        featured: true,
        posted: "1 day ago",
        postedBy: "admin_1",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "3",
        title: "Backend Core Intern",
        company: "Razorpay",
        companyLogo: "🚀",
        location: "Mumbai · Hybrid",
        city: "Mumbai",
        type: "Internship",
        mode: "Hybrid",
        salaryMin: 25000,
        salaryMax: 35000,
        salary: "₹25K–₹35K/mo",
        description: "Scale our payment systems to handle millions of transactions...",
        responsibilities: ["API development", "DB management"],
        requirements: ["Node.js", "MongoDB"],
        tags: ["Node.js", "Express", "Mongo"],
        openings: 5,
        deadline: "2026-03-30",
        featured: false,
        posted: "3 hours ago",
        postedBy: "admin_1",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "4",
        title: "Product Designer",
        company: "Airbnb",
        companyLogo: "🏠",
        location: "Gurgaon · Onsite",
        city: "Gurgaon",
        type: "Full-time",
        mode: "Onsite",
        salaryMin: 90000,
        salaryMax: 150000,
        salary: "₹90K–₹1.5L/mo",
        description: "Craft unique travel experiences through design...",
        responsibilities: ["UI/UX design", "Prototyping"],
        requirements: ["Figma", "Visual design"],
        tags: ["Figma", "UI/UX"],
        openings: 1,
        deadline: "2026-06-01",
        featured: false,
        posted: "5 days ago",
        postedBy: "admin_1",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];
